//! Recovery helpers for the Special/name cipher parameters generated by
//! `Storages.setupArchiveData` in the embedded protection module.
//!
//! Reverse engineering of the native initializer shows two deterministic
//! stages:
//!   1. `control[4096] = SHAKE256(archive_data_bytes)`
//!   2. `digest = BLAKE2s-128(key=archive_data_bytes[..min(len,32)], data=control)`
//!      digest DWORD 0 derives the content split mask/offset, while DWORDs 2
//!      and 3 are the Special seed words.
//!
//! The TJS entry point passes the string as UTF-16LE bytes and explicitly
//! excludes the terminating NUL (`length * 2`).

use crate::{Error, Result, SpecialFixedParams};
use blake2::{
    digest::{consts::U16, KeyInit, Mac},
    Blake2sMac,
};
use sha3::{
    digest::{ExtendableOutput, Update, XofReader},
    Shake256,
};
use std::collections::{BTreeMap, BTreeSet};

pub const ARCHIVE_CONTROL_BYTES: usize = 4096;
const MAX_ARCHIVE_DATA_BYTES: usize = 64 * 1024;
const MAX_SCRIPT_CANDIDATES: usize = 16 * 1024;
const MAX_SCRIPT_LITERAL_UNITS: usize = MAX_ARCHIVE_DATA_BYTES / 2;

type Blake2sMac128 = Blake2sMac<U16>;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DerivedSpecialParams {
    pub archive_data: Vec<u8>,
    pub control_block: Vec<u8>,
    /// Content split boundary is `(hash & mask) + offset`.  These values are
    /// generated by the same native initializer as the Special seeds.
    pub mask: u32,
    pub offset: u32,
    pub fixed: SpecialFixedParams,
}

pub fn derive_special_params_from_archive_data_bytes(input: &[u8]) -> Result<DerivedSpecialParams> {
    if input.is_empty() || input.len() > MAX_ARCHIVE_DATA_BYTES {
        return Err(Error::invalid(format!(
            "setupArchiveData byte length {} is outside 1..={MAX_ARCHIVE_DATA_BYTES}",
            input.len()
        )));
    }

    let mut shake = Shake256::default();
    shake.update(input);
    let mut reader = shake.finalize_xof();
    let mut control_block = vec![0u8; ARCHIVE_CONTROL_BYTES];
    reader.read(&mut control_block);

    let key_len = input.len().min(32);
    let mut mac = <Blake2sMac128 as KeyInit>::new_from_slice(&input[..key_len])
        .map_err(|_| Error::invalid("invalid BLAKE2s setupArchiveData key length"))?;
    Mac::update(&mut mac, &control_block);
    let digest = mac.finalize().into_bytes();

    let mut control_words = [0u32; 8];
    for (index, word) in control_words.iter_mut().enumerate() {
        let offset = index * 4;
        let generated = u32::from_le_bytes(
            control_block[offset..offset + 4]
                .try_into()
                .expect("32-byte control prefix"),
        );
        // The native Special-state constructor (the function called from
        // 0x1000f0f0 in the embedded yuzu_cxdec_tpm.dll) loads each of the
        // first eight generated control DWORDs and applies NOT before writing
        // state[4..12].  `SpecialFixedParams::base_state()` expects exactly
        // that stored-state representation, so the Special words are the
        // complements of the raw SHAKE256 control block.  The full raw
        // `control_block` is retained unchanged because the ordinary CXDEC
        // content path consumes the generated/encoded representation.
        *word = !generated;
    }
    // Native code uses the first digest DWORD to initialize the content
    // split parameters:
    //   mask   = (d0 & 0x1ff) + 0x100
    //   offset = ((d0 >> 9) & 0x7f) + ((d0 >> 16) & 0xff) + 0x20
    // and stores digest DWORDs 2/3 as the two Special seed words.
    let d0 = u32::from_le_bytes(digest[0..4].try_into().unwrap());
    let mask = (d0 & 0x1ff).wrapping_add(0x100);
    let offset = ((d0 >> 9) & 0x7f)
        .wrapping_add((d0 >> 16) & 0xff)
        .wrapping_add(0x20);
    let seed0 = u32::from_le_bytes(digest[8..12].try_into().unwrap());
    let seed1 = u32::from_le_bytes(digest[12..16].try_into().unwrap());

    Ok(DerivedSpecialParams {
        archive_data: input.to_vec(),
        control_block,
        mask,
        offset,
        fixed: SpecialFixedParams::new(control_words, seed0, seed1),
    })
}

pub fn derive_special_params_from_archive_data_text(text: &str) -> Result<DerivedSpecialParams> {
    let mut bytes = Vec::with_capacity(text.len().saturating_mul(2));
    for unit in text.encode_utf16() {
        bytes.extend_from_slice(&unit.to_le_bytes());
    }
    derive_special_params_from_archive_data_bytes(&bytes)
}

/// Recover values passed to `Storages.setupArchiveData`.
///
/// Compiled TJS2 is handled semantically: the bytecode is lowered through
/// tjs2dec and bounded symbolic execution records only values that actually
/// reach a `setupArchiveData` call.  String-pool entries by themselves are not
/// candidates.  Source TJS keeps a small constant-expression fallback.  Final
/// acceptance is always the real Special decrypt/decompress/index validator.
pub fn setup_archive_data_text_candidates(bytes: &[u8]) -> Vec<String> {
    let wrapped = crate::validate::decode_kirikiri_text(bytes);
    let mut byte_views = Vec::<Vec<u8>>::new();
    byte_views.push(bytes.to_vec());
    if let Some(decoded) = wrapped.as_ref() {
        if decoded.as_slice() != bytes {
            byte_views.push(decoded.clone());
        }
    }

    let mut out = BTreeSet::<String>::new();
    let mut saw_tjs2 = false;

    // Compiled TJS2 is not a bag of string candidates.  The DATA pool only
    // supplies constants to bytecode.  Accept a string here only when bounded
    // symbolic execution proves that the value reaches an actual
    // Storages.setupArchiveData(...) call.
    for view in &byte_views {
        if !view.starts_with(b"TJS2100\0") {
            continue;
        }
        saw_tjs2 = true;
        if let Ok(report) = crate::tjs_symexec::symbolically_execute_tjs2(view) {
            for call in report.setup_archive_data_calls {
                if let Some(argument) = call.argument {
                    insert_candidate(&mut out, argument);
                }
            }
        }
    }
    if saw_tjs2 {
        return out.into_iter().collect();
    }

    // Source/wrapped TJS is handled separately.  Here the text itself is the
    // program representation, so direct calls and small constant expressions
    // can be recovered without guessing from unrelated binary constants.
    let wrapped_script = wrapped.is_some();
    let mut decoded_texts = Vec::<String>::new();
    for view in &byte_views {
        if let Ok(text) = std::str::from_utf8(view) {
            decoded_texts.push(text.to_string());
        } else {
            let (text, _, _) = encoding_rs::SHIFT_JIS.decode(view);
            decoded_texts.push(text.into_owned());
        }

        if view.len() >= 2 && view.len() % 2 == 0 {
            let mut nul_high = 0usize;
            let mut pairs = 0usize;
            for pair in view.chunks_exact(2).take(4096) {
                pairs += 1;
                if pair[1] == 0 {
                    nul_high += 1;
                }
            }
            if view.starts_with(&[0xff, 0xfe]) || (pairs != 0 && nul_high * 3 >= pairs) {
                let start = usize::from(view.starts_with(&[0xff, 0xfe])) * 2;
                let units = view[start..]
                    .chunks_exact(2)
                    .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
                    .collect::<Vec<_>>();
                decoded_texts.push(String::from_utf16_lossy(&units));
            }
        }
    }

    for text in decoded_texts {
        if !wrapped_script && !looks_like_tjs_source(&text) {
            continue;
        }

        if let Some(argument) = direct_setup_argument(&text) {
            insert_candidate(&mut out, argument);
        }
        // Source TJS has no separate bytecode/string-pool ambiguity.  Keep the
        // legacy high-recall literals here; Special validation still decides
        // acceptance.  Compiled TJS2 never takes this path.
        extend_candidate_set(&mut out, string_literals(&text));
        extend_candidate_set(&mut out, constant_string_concatenations(&text));
        extend_candidate_set(&mut out, resolved_string_expressions(&text));
        if out.len() >= MAX_SCRIPT_CANDIDATES {
            break;
        }
    }

    out.into_iter().collect()
}

fn insert_candidate(out: &mut BTreeSet<String>, value: String) {
    if out.len() >= MAX_SCRIPT_CANDIDATES {
        return;
    }
    if value.is_empty() || value.encode_utf16().count() > MAX_SCRIPT_LITERAL_UNITS {
        return;
    }
    // setupArchiveData receives a TJS string; embedded NUL/control-heavy values
    // cannot be supplied by the observed native string path and are useless as
    // archive-data candidates.
    if value.chars().any(|ch| ch == '\0' || (ch.is_control() && !matches!(ch, '\t' | '\r' | '\n'))) {
        return;
    }
    out.insert(value);
}

fn extend_candidate_set<I>(out: &mut BTreeSet<String>, values: I)
where
    I: IntoIterator<Item = String>,
{
    for value in values {
        insert_candidate(out, value);
        if out.len() >= MAX_SCRIPT_CANDIDATES {
            break;
        }
    }
}

fn looks_like_tjs_source(text: &str) -> bool {
    let sample = text.get(..text.len().min(256 * 1024)).unwrap_or(text);
    sample.contains("setupArchiveData")
        || sample.contains("Storages.")
        || sample.contains("System.")
        || sample.contains("function ")
        || sample.contains("class ")
        || sample.contains("var ")
        || sample.contains("property ")
        || sample.contains("//@set")
}

/// Recover compile-time string concatenations such as
/// `"part1" + "part2"`.  This also covers a variable assignment followed by
/// `setupArchiveData(variable)`, because the constant expression itself is
/// present in the same script.  Dynamic concatenations are intentionally not
/// guessed here.
fn constant_string_concatenations(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut at = 0usize;
    while at < text.len() && out.len() < MAX_SCRIPT_CANDIDATES {
        let Some(ch) = text[at..].chars().next() else {
            break;
        };
        if ch != '\'' && ch != '"' {
            at += ch.len_utf8();
            continue;
        }
        let Some((first, consumed)) = parse_quoted(&text[at..]) else {
            at += ch.len_utf8();
            continue;
        };
        let mut value = first;
        let mut cursor = at + consumed;
        let mut parts = 1usize;

        loop {
            cursor = skip_ascii_space(text, cursor);
            if text.as_bytes().get(cursor) != Some(&b'+') {
                break;
            }
            cursor += 1;
            cursor = skip_ascii_space(text, cursor);
            let Some(next) = text.get(cursor..) else {
                break;
            };
            let Some(next_ch) = next.chars().next() else {
                break;
            };
            if next_ch != '\'' && next_ch != '"' {
                break;
            }
            let Some((piece, used)) = parse_quoted(next) else {
                break;
            };
            if value.encode_utf16().count().saturating_add(piece.encode_utf16().count())
                > MAX_SCRIPT_LITERAL_UNITS
            {
                break;
            }
            value.push_str(&piece);
            parts += 1;
            cursor += used;
        }

        if parts >= 2 {
            out.push(value);
            at = cursor.max(at + consumed);
        } else {
            at += consumed.max(ch.len_utf8());
        }
    }
    out
}

fn resolved_string_expressions(text: &str) -> Vec<String> {
    let mut env = BTreeMap::<String, String>::new();
    let mut out = Vec::<String>::new();

    for statement in tjs_statements(text) {
        let trimmed = statement.trim();
        if let Some((name, rhs)) = simple_assignment(trimmed) {
            if let Some(value) = eval_string_expr(rhs, &env) {
                if value.encode_utf16().count() <= MAX_SCRIPT_LITERAL_UNITS {
                    env.insert(name.to_string(), value.clone());
                    out.push(value);
                }
            }
        }
    }

    // Resolve setupArchiveData(identifier-or-constant-expression) after the
    // assignment pass.  This handles the common bootstrap form where the
    // archive string is assembled in one or more preceding statements.
    let marker = "setupArchiveData";
    let mut search = 0usize;
    while let Some(relative) = text.get(search..).and_then(|tail| tail.find(marker)) {
        let mut at = search + relative + marker.len();
        at = skip_ascii_space(text, at);
        if text.as_bytes().get(at) != Some(&b'(') {
            search = at.min(text.len());
            continue;
        }
        let Some((inside, consumed)) = parenthesized_expression(text, at) else {
            break;
        };
        if let Some(value) = eval_string_expr(inside, &env) {
            out.push(value);
        }
        search = at.saturating_add(consumed).min(text.len());
    }

    out
}

fn tjs_statements(text: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut start = 0usize;
    let mut quote = None::<char>;
    let mut escaped = false;
    let mut depth = 0usize;
    for (at, ch) in text.char_indices() {
        if let Some(q) = quote {
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == q {
                quote = None;
            }
            continue;
        }
        match ch {
            '\'' | '"' => quote = Some(ch),
            '(' | '[' => depth = depth.saturating_add(1),
            ')' | ']' => depth = depth.saturating_sub(1),
            ';' if depth == 0 => {
                if let Some(statement) = text.get(start..at) {
                    out.push(statement);
                }
                start = at + 1;
            }
            _ => {}
        }
    }
    if start < text.len() {
        if let Some(statement) = text.get(start..) {
            out.push(statement);
        }
    }
    out
}

fn simple_assignment(statement: &str) -> Option<(&str, &str)> {
    let statement = statement.trim();
    let statement = statement
        .rsplit_once('{')
        .map(|(_, tail)| tail)
        .unwrap_or(statement)
        .trim();
    let statement = statement.strip_prefix("var ").unwrap_or(statement).trim_start();
    let bytes = statement.as_bytes();
    let mut quote = None::<u8>;
    let mut escaped = false;
    let mut depth = 0usize;
    for at in 0..bytes.len() {
        let byte = bytes[at];
        if let Some(q) = quote {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == q {
                quote = None;
            }
            continue;
        }
        match byte {
            b'\'' | b'"' => quote = Some(byte),
            b'(' | b'[' | b'{' => depth = depth.saturating_add(1),
            b')' | b']' | b'}' => depth = depth.saturating_sub(1),
            b'=' if depth == 0 => {
                if bytes.get(at.wrapping_sub(1)) == Some(&b'=')
                    || bytes.get(at + 1) == Some(&b'=')
                    || bytes.get(at.wrapping_sub(1)) == Some(&b'!')
                    || bytes.get(at.wrapping_sub(1)) == Some(&b'<')
                    || bytes.get(at.wrapping_sub(1)) == Some(&b'>')
                {
                    continue;
                }
                let lhs = statement.get(..at)?.trim();
                if !is_simple_identifier(lhs) {
                    return None;
                }
                return Some((lhs, statement.get(at + 1..)?.trim()));
            }
            _ => {}
        }
    }
    None
}

fn is_simple_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn eval_string_expr<'a>(expr: &'a str, env: &BTreeMap<String, String>) -> Option<String> {
    let mut expr = expr.trim();
    while expr.starts_with('(') && expr.ends_with(')') {
        let (inside, consumed) = parenthesized_expression(expr, 0)?;
        if consumed != expr.len() {
            break;
        }
        expr = inside.trim();
    }

    let mut out = String::new();
    let mut at = 0usize;
    let mut terms = 0usize;
    loop {
        at = skip_ascii_space(expr, at);
        if at >= expr.len() {
            break;
        }
        let tail = expr.get(at..)?;
        let ch = tail.chars().next()?;
        if ch == '\'' || ch == '"' {
            let (value, consumed) = parse_quoted(tail)?;
            out.push_str(&value);
            at += consumed;
        } else {
            let len = tail
                .char_indices()
                .take_while(|(_, ch)| *ch == '_' || ch.is_ascii_alphanumeric())
                .map(|(i, ch)| i + ch.len_utf8())
                .last()?;
            let name = tail.get(..len)?;
            if !is_simple_identifier(name) {
                return None;
            }
            out.push_str(env.get(name)?);
            at += len;
        }
        terms += 1;
        if out.encode_utf16().count() > MAX_SCRIPT_LITERAL_UNITS {
            return None;
        }
        at = skip_ascii_space(expr, at);
        if at >= expr.len() {
            break;
        }
        if expr.as_bytes().get(at) != Some(&b'+') {
            return None;
        }
        at += 1;
    }
    (terms != 0).then_some(out)
}

fn parenthesized_expression(text: &str, open: usize) -> Option<(&str, usize)> {
    if text.as_bytes().get(open) != Some(&b'(') {
        return None;
    }
    let mut quote = None::<u8>;
    let mut escaped = false;
    let mut depth = 0usize;
    let bytes = text.as_bytes();
    let mut at = open;
    while at < bytes.len() {
        let byte = bytes[at];
        if let Some(q) = quote {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == q {
                quote = None;
            }
            at += 1;
            continue;
        }
        match byte {
            b'\'' | b'"' => quote = Some(byte),
            b'(' => depth += 1,
            b')' => {
                depth = depth.checked_sub(1)?;
                if depth == 0 {
                    return Some((text.get(open + 1..at)?, at + 1 - open));
                }
            }
            _ => {}
        }
        at += 1;
    }
    None
}

fn skip_ascii_space(text: &str, mut at: usize) -> usize {
    while let Some(byte) = text.as_bytes().get(at) {
        if !byte.is_ascii_whitespace() {
            break;
        }
        at += 1;
    }
    at
}

fn direct_setup_argument(text: &str) -> Option<String> {
    let marker = "setupArchiveData";
    let at = text.find(marker)? + marker.len();
    let rest = text.get(at..)?.trim_start();
    let rest = rest.strip_prefix('(')?.trim_start();
    parse_quoted(rest).map(|(value, _)| value)
}

fn string_literals(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut at = 0usize;
    while at < text.len() && out.len() < MAX_SCRIPT_CANDIDATES {
        let Some(ch) = text[at..].chars().next() else {
            break;
        };
        if ch != '\'' && ch != '"' {
            at += ch.len_utf8();
            continue;
        }
        if let Some((value, consumed)) = parse_quoted(&text[at..]) {
            if value.encode_utf16().count() <= MAX_SCRIPT_LITERAL_UNITS {
                out.push(value);
            }
            at += consumed.max(ch.len_utf8());
        } else {
            at += ch.len_utf8();
        }
    }
    out
}

fn parse_quoted(text: &str) -> Option<(String, usize)> {
    let quote = text.chars().next()?;
    if quote != '\'' && quote != '"' {
        return None;
    }
    let mut out = String::new();
    let mut escaped = false;
    let mut consumed = quote.len_utf8();
    for ch in text[consumed..].chars() {
        consumed += ch.len_utf8();
        if escaped {
            match ch {
                'n' => out.push('\n'),
                'r' => out.push('\r'),
                't' => out.push('\t'),
                '\\' => out.push('\\'),
                '\'' => out.push('\''),
                '"' => out.push('"'),
                other => out.push(other),
            }
            escaped = false;
            continue;
        }
        if ch == '\\' {
            escaped = true;
            continue;
        }
        if ch == quote {
            return Some((out, consumed));
        }
        out.push(ch);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn archive_data_derivation_matches_independent_vector() {
        let derived = derive_special_params_from_archive_data_text("archive-test").unwrap();
        assert_eq!(
            &derived.control_block[..32],
            &hex("92727ce979bf1a5801892eceff4c671a3cd0a5c9771f25ea7813bbacb6265560")
        );
        assert_eq!(derived.mask, 0x28a);
        assert_eq!(derived.offset, 0x06f);
        assert_eq!(derived.fixed.seed0, 0x504f_638e);
        assert_eq!(derived.fixed.seed1, 0xf983_c1cf);
    }

    #[test]
    fn yuzu_setup_string_matches_riddle_joker_native_vector() {
        let derived = derive_special_params_from_archive_data_text(
            "(C)YUZUSOFT/JUNOS_INC.All_Rights_Reserved.",
        )
        .unwrap();
        assert_eq!(
            &derived.control_block[..64],
            &hex(concat!(
                "beed7e41444ce26c2e97830ccf01f426",
                "e9cf1d6651e4e8da4ea1ef0bbe0d70db",
                "dfbbc45b9fcbfee2ced6ccc6c000459b",
                "1a3e27cec1949651cd550802e101d5cc",
            ))
        );
        assert_eq!(derived.mask, 0x118);
        assert_eq!(derived.offset, 0x10f);
        assert_eq!(derived.fixed.seed0, 0xbdd7_2518);
        assert_eq!(derived.fixed.seed1, 0xd541_d24c);
    }

    #[test]
    fn extracts_direct_and_neighbor_literals() {
        let src = br#"Storages.setupArchiveData("secret"); var other = 'nearby';"#;
        let values = setup_archive_data_text_candidates(src);
        assert!(values.iter().any(|value| value == "secret"));
        assert!(values.iter().any(|value| value == "nearby"));
    }

    #[test]
    fn extracts_script_literals_without_setup_member_marker() {
        let src = br#"var archive_seed = "secret-without-member-name"; function boot() { return archive_seed; }"#;
        let values = setup_archive_data_text_candidates(src);
        assert!(values
            .iter()
            .any(|value| value == "secret-without-member-name"));
    }

    #[test]
    fn extracts_constant_string_concatenation_without_setup_member_marker() {
        let src = br#"var archive_seed = "secret-" + 'joined'; function boot() { return archive_seed; }"#;
        let values = setup_archive_data_text_candidates(src);
        assert!(values.iter().any(|value| value == "secret-joined"));
    }

    #[test]
    fn resolves_simple_variable_chain_for_setup_argument() {
        let src = br#"var left = "archive-"; var key = left + 'secret'; Storages.setupArchiveData(key);"#;
        let values = setup_archive_data_text_candidates(src);
        assert!(values.iter().any(|value| value == "archive-secret"));
    }

    #[test]
    fn does_not_treat_tjs2_string_pool_as_setup_argument() {
        let mut data = Vec::new();
        for count in [0u32, 0, 0, 0, 0] {
            data.extend_from_slice(&count.to_le_bytes());
        }
        let strings = ["setupArchiveData", "archive-secret"];
        data.extend_from_slice(&(strings.len() as u32).to_le_bytes());
        for value in strings {
            let units = value.encode_utf16().collect::<Vec<_>>();
            data.extend_from_slice(&(units.len() as u32).to_le_bytes());
            for unit in &units {
                data.extend_from_slice(&unit.to_le_bytes());
            }
            if units.len() & 1 != 0 {
                data.extend_from_slice(&[0, 0]);
            }
        }

        let mut bytecode = b"TJS2100\0".to_vec();
        bytecode.extend_from_slice(&0u32.to_le_bytes());
        bytecode.extend_from_slice(b"DATA");
        bytecode.extend_from_slice(&((data.len() + 8) as u32).to_le_bytes());
        bytecode.extend_from_slice(&data);
        let declared = bytecode.len() as u32;
        bytecode[8..12].copy_from_slice(&declared.to_le_bytes());

        let values = setup_archive_data_text_candidates(&bytecode);
        assert!(!values.iter().any(|value| value == "archive-secret"));
    }

    #[test]
    fn does_not_treat_unrelated_tjs2_pool_string_as_setup_argument() {
        let mut data = Vec::new();
        for count in [0u32, 0, 0, 0, 0] {
            data.extend_from_slice(&count.to_le_bytes());
        }
        let strings = ["unrelatedMember", "archive-secret-no-marker"];
        data.extend_from_slice(&(strings.len() as u32).to_le_bytes());
        for value in strings {
            let units = value.encode_utf16().collect::<Vec<_>>();
            data.extend_from_slice(&(units.len() as u32).to_le_bytes());
            for unit in &units {
                data.extend_from_slice(&unit.to_le_bytes());
            }
            if units.len() & 1 != 0 {
                data.extend_from_slice(&[0, 0]);
            }
        }

        let mut bytecode = b"TJS2100\0".to_vec();
        bytecode.extend_from_slice(&0u32.to_le_bytes());
        bytecode.extend_from_slice(b"DATA");
        bytecode.extend_from_slice(&((data.len() + 8) as u32).to_le_bytes());
        bytecode.extend_from_slice(&data);
        let declared = bytecode.len() as u32;
        bytecode[8..12].copy_from_slice(&declared.to_le_bytes());

        let values = setup_archive_data_text_candidates(&bytecode);
        assert!(!values
            .iter()
            .any(|value| value == "archive-secret-no-marker"));
    }

    fn hex(value: &str) -> Vec<u8> {
        value
            .as_bytes()
            .chunks_exact(2)
            .map(|pair| {
                u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16).unwrap()
            })
            .collect()
    }
}

/// Structural recognition of the native `setupArchiveData` parameter
/// generator.  No title/module/tag names are used: the evidence is the TJS
/// member name plus the SHAKE256 parameter tuple and the complemented ChaCha
/// sigma consumed by the Special cipher.
pub fn has_setup_archive_data_special_generator(module: &[u8]) -> bool {
    let mut setup_utf16 = Vec::new();
    for unit in "setupArchiveData".encode_utf16() {
        setup_utf16.extend_from_slice(&unit.to_le_bytes());
    }
    if !module.windows(setup_utf16.len()).any(|window| window == setup_utf16) {
        return false;
    }

    let mut sigma = Vec::with_capacity(16);
    for word in crate::special_cipher::COMPLEMENTED_CHACHA_SIGMA {
        sigma.extend_from_slice(&word.to_le_bytes());
    }
    if !module.windows(sigma.len()).any(|window| window == sigma) {
        return false;
    }

    // Native call site pushes SHAKE256's domain suffix, capacity, rate and
    // requested 4096-byte output size immediately before the XOF helper.
    const SHAKE_CALL_ARGS: &[u8] = &[
        0x6a, 0x1f,                         // push 0x1f domain suffix
        0x68, 0x00, 0x02, 0x00, 0x00,       // push 0x200 capacity bits
        0x68, 0x40, 0x04, 0x00, 0x00,       // push 0x440 rate bits
        0x68, 0x00, 0x10, 0x00, 0x00,       // push 0x1000 output bytes
    ];
    module
        .windows(SHAKE_CALL_ARGS.len())
        .any(|window| window == SHAKE_CALL_ARGS)
}
